spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl: true

# Production Notification Settings
notification:
  email:
    provider: aws-ses
    from-address: ${PROD_EMAIL_FROM}
    enabled: true

  sms:
    provider: aws-sns
    from-number: ${PROD_SMS_FROM}
    enabled: true

  template:
    storage: aws-s3
    cache-enabled: true

# AWS Configuration for Production
aws:
  enabled: true
  region: ${AWS_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: ${AWS_S3_BUCKET}

logging:
  level:
    com.iam.notification: INFO
    software.amazon.awssdk: WARN
