spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/iam_db
    username: iam_malak
    password: Malak123

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

  # SMTP Configuration for Development
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_EMAIL_USERNAME:your-email@gmail.com}
    password: ${DEV_EMAIL_PASSWORD:your-app-password}

# Development Notification Settings
notification:
  email:
    provider: smtp
    from-address: ${DEV_EMAIL_USERNAME:noreply@iam-system.com}
    enabled: true

  sms:
    provider: mock
    enabled: true

  template:
    storage: file
    cache-enabled: false  # Disable cache for development

aws:
  enabled: false

logging:
  level:
    com.iam.notification: DEBUG
    org.springframework.mail: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
